like:
  upload-directory: D:/upload/
  captcha:
    status: true
    expire: 120
    token: "captcha:key:"
  swagger:
    enabled: true
    pathMapping: /dev-api
server:
  port: 8082
spring:
  mvc:
    static-path-pattern: /api/static/**
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySql的驱动
    url: jdbc:mysql://124.222.66.151:3306/like?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型
    username: zss98 # 数据库账号
    password: zss980909 # 数据库密码
  servlet:
    multipart:
      max-file-size: 100MB    # 文件上传大小限制
      max-request-size: 100MB # 文件最大请求限制
      enabled: true
  # Redis配置
  redis:
    host: 124.222.66.151   # Redis服务地址
    port: 12345        # Redis端口
    password: zss980909       # Redis密码
    database: 0       # 数据库索引
    timeout: 5000     # 连接超时
    lettuce:
      pool:
        max-wait: 30000 # 连接池最大阻塞等待时间(使用负数表示没有限制,默认-1)
        max-active: 100 # 连接池最大连接数(使用负数表示没有限制,默认8)
        max-idle: 20    # 连接池中的最大空闲连接(默认8)
        min-idle: 0     # 连接池中的最小空闲连接(默认0)
# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

# Sa-token配置
sa-token:
  token-name: manger  # token的名称
  timeout: 2592000        # token有效期单位s(默认30天,-1代表永不过期)
  activity-timeout: -1    # token临时有效期(指定时间无操作掉线)
  is-concurrent: true     # 是否允许同一账号并发登录
  is-share: false         # 多人同登账号共用token
  token-style: random-64  # token生成的风格
  is-print: false         # 打印版本字符画
  is-log: false           # 是否输出操作日志